name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Yarn install cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install && yarn --cwd exporter install
      - name: Cache graph
        id: cache-graph
        uses: actions/cache@v3
        with:
          path: .
          key: ${{ runner.os }}-graph-${{ hashFiles('**/*graph.json') }}
      - name: Fetch graph conf
        env:
          CONF_URL: "${{ vars.CONF_URL }}"
        steps:
          run: wget -O config.json "$CONF_URL"
        - id: set_var
          run: |
            content=`cat ./config.json`
            # the following lines are only required for multi line json
            content="${content//'%'/'%25'}"
            content="${content//$'\n'/'%0A'}"
            content="${content//$'\r'/'%0D'}"
            # end of optional handling for multi line json
            echo "::set-output name=configJson::$content"
        - run: |
            echo "${{fromJson(steps.set_var.outputs.configJson).settings.graphVersion}}"
      - name: Fetch graph data
        env:
          GRAPH_URL: "${{ vars.GRAPH_URL }}"
        steps:
          run: wget -O graph.json "$GRAPH_URL"
          run: |
            cd exporter
            yarn getGraphVersion >> $GRAPH_VERSION
        if: steps.cache-graph.outputs.cache-hit != 'true' || fromJson(steps.set_var.outputs.configJson).settings.graphVersion != vars.GRAPH_VERSION
      - name: Cache layouts
        id: cache-layouts
        uses: actions/cache@v3
        with:
          path: ./exporter/out/
          key: ${{ runner.os }}-exporter-out-${{ hashFiles('**/*.json') }}
      - name: Generate layout
        run: |
          mkdir -p exporter/out
          cd exporter
          yarn start graph.json
      - name: Build
        run: |
          yarn build
          mkdir -p dist/exporter/out
          cp -rv exporter/out/* dist/exporter/out/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'


  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
