name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Yarn install cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install && yarn --cwd exporter install
      - name: Fetch graph data
        env:
          GRAPH_URL: "${{ vars.GRAPH_URL }}"
        run: wget -O graph.json "$GRAPH_URL"
      - name: Fetch graph conf
        env:
          CONF_URL: "${{ vars.CONF_URL }}"
        run: wget -O config.json "$CONF_URL"
      - name: Generate layout
        id: generate-layout
        uses: actions/cache@v3
        with:
          path: ./exporter/out/
          key: ${{ runner.os }}-exporter-out-${{ hashFiles('**/*.json') }}
        run: |
          mkdir exporter/out
          cd exporter
          yarn start graph.json
      - name: Build
        run: |
          yarn build
          mkdir -p dist/exporter/out
          cp -rv exporter/out/* dist/exporter/out/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'


  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
